[package]
name = "elly-fish"
version = "1.0.0"
description = "Elly Fish Desktop App"
authors = ["Elly Fish"]
license = ""
repository = ""
edition = "2021"

# This feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
[features]
custom-protocol = ["tauri/custom-protocol"]

# Prevent console window from appearing on Windows in release
[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.7", features = [ "updater",
  "devtools",
  "notification-all",
  "shell-open",
  "system-tray",
  "window-close",
  "window-hide",
  "window-maximize",
  "window-minimize",
  "window-set-fullscreen",
  "window-set-size",
  "window-set-title",
  "window-show",
  "window-center"
] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dirs = "5"
