export const API_ROUTES = {
  LOGIN: `auth/login`,
  USER: `users`,
  COMPANY: `companies`,
  CATEGORY: `categories`,
  SETTING: `settings`,
  ORDER: `orders`,
  ORDER_ATTACHMENT: `orderattachments`,
  ORDER_CHAT: `orderchats`,
  ORDER_REMINDER: `orderreminders`,
  ORDER_CLIENT: `orderclients`,
  ORDER_PAYMENT: `orderpayments`,
  ORDER_ACTIVITY: `orderactivities`,
  USER_PAYMENT: `userpayments`,
  WORK_ORDER: `workorders`,
  NOTIFICATION: `notifications`,
  ORDERS_INQUIRY:`all-search-for-inquiry`,
  AUTH_ACTIVITY: `auth-activity`,
  QUERY: `queries`,
  INVOICE: `invoices`,
};
