export const API_ROUTES = {
  LOGIN: `auth/login`,
  SELECT_ROLE: `auth/select-role`,
  USER: `users`,
  COMPANY: `companies`,
  CATEGORY: `categories`,
  SETTING: `settings`,
  ORDER: `orders`,
  ORDER_ATTACHMENT: `orderattachments`,
  ORDER_CHAT: `orderchats`,
  ORDER_REMINDER: `orderreminders`,
  ORDER_CLIENT: `orderclients`,
  ORDER_PAYMENT: `orderpayments`,
  ORDER_ACTIVITY: `orderactivities`,
  USER_PAYMENT: `userpayments`,
  WORK_ORDER: `workorders`,
  NOTIFICATION: `notifications`,
  ORDERS_INQUIRY:`all-search-for-inquiry`,
  AUTH_ACTIVITY: `auth-activity`,
  QUERY: `queries`,
  INVOICE: `invoices`,
  GROUP_CHAT: `group-chat`,
  CLIENT: `clients`,
  CLIENT_CONTACT: `client-contacts`,
  ORDER_CONTACT: `order-contacts`,
  WARNING: `warnings`,
  CLIENT_VISIT: `client-visits`,
  OLD_INQUIRY: `old-inquiries`,
  ORDER_FEEDBACK: `order-feedbacks`,
  MEDIA: `media`,
};
